# YAML anchors
shared:
  - &task-merge-stack-and-config
    task: merge-stack-and-config
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cycloid/cycloid-toolkit
          tag: latest
      run:
        path: /usr/bin/merge-stack-and-config
      inputs:
        - name: git_config
          path: "config"
        - name: git_stack
          path: "stack"
      outputs:
        - name: merged-stack/stack-lambda/terraform
          path: "merged-stack"
    params:
      CONFIG_PATH: ((project))/terraform/((env))
      STACK_PATH: stack-lambda/terraform

groups:
  - name: all
    jobs:
    - lambda-build
    - unittest
    - terraform-plan
    - terraform-apply
    - functional-tests

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: '0.11.13'

  - name: cycloid-events
    type: docker-image
    source:
      repository: cycloid/cycloid-events-resource

resources:
  - name: git_lambda-code
    type: git
    check_every: 2m
    source:
      uri: ((lambda_git_repository))
      branch: ((lambda_git_branch))
      private_key: ((lambda_git_ssh_key))

  - name: git_stack
    type: git
    check_every: 2m
    source:
      uri: ((lambda_git_repository))
      branch: stacks
      private_key: ((lambda_git_ssh_key))
      paths:
        - stack-lambda/terraform/*

  - name: git_config
    type: git
    check_every: 2m
    source:
      uri: ((lambda_git_repository))
      branch: ((config_git_branch))
      private_key: ((lambda_git_ssh_key))

  - name: s3_lambda-release
    type: s3
    source:
      bucket: ((lambda_release_bucket_name))
      versioned_file: ((lambda_release_bucket_object_path))
      private: true
      region_name: ((aws_default_region))
      access_key_id: ((aws_access_key))
      secret_access_key: ((aws_secret_key))

  - name: tfstate
    type: terraform
    source:
      env_name: ((env))
      backend_type: s3
      backend_config:
        bucket: ((terraform_storage_bucket_name))
        key: ((terraform_storage_bucket_path))/terraform.tfstate
        region: ((aws_default_region))
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))
      vars:
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))
        aws_region: ((aws_default_region))
        env: ((env))
        project: ((project))
        customer: ((customer))

  - name: cycloid-events
    type: cycloid-events
    source:
      api_login: ((api_login))
      api_password: ((api_password))
      api_url: ((api_url))
      icon: fa-code-branch
      organization: ((customer))
      severity: info
      type: Custom
      tags:
        - key: project
          value: ((project))
        - key: env
          value: ((env))
        - key: customer
          value: ((customer))

jobs:
  - name: lambda-build
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: git_lambda-code
        trigger: true

      - task: build-release
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              DIR=${PWD}
              cd ${DIR}/code/
              zip -r ${DIR}/release/((project)).zip *
          inputs:
          - name: git_lambda-code
            path: code
          outputs:
          - name: release
            path: "release"

      - put: s3_lambda-release
        params:
          acl: private
          file: release/((project)).zip

  - name: unittest
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: git_lambda-code
        passed: [lambda-build]
      - get: s3_lambda-release
        trigger: true
        passed: [lambda-build]

      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              unzip code/((project)).zip
          inputs:
          - name: s3_lambda-release
            path: code

  - name: terraform-plan
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: git_lambda-code
        passed: [unittest]
      - get: s3_lambda-release
        passed: [unittest]
        trigger: true
      - get: git_stack
        trigger: true
      - get: git_config
        trigger: true
      - *task-merge-stack-and-config
      - put: tfstate
        params:
          env_name: ((env))
          plan_only: true
          terraform_source: merged-stack/stack-lambda/terraform

  - name: terraform-apply
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: git_lambda-code
        passed: [terraform-plan]
      - get: s3_lambda-release
        passed: [terraform-plan]
      - get: git_stack
        passed: [terraform-plan]
      - get: tfstate
        passed: [terraform-plan]
      - get: git_config
        passed: [terraform-plan]
      - *task-merge-stack-and-config
      - put: tfstate
        params:
          env_name: ((env))
          plan_run: true
          terraform_source: merged-stack/stack-lambda/terraform

  - name: functional-tests
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: tfstate
        passed: [terraform-apply]
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              export LAMBDA_ARN=$(cat tfstate/metadata | jq -r .lambda_function_arn)
              aws lambda invoke --function-name $LAMBDA_ARN  result
              cat result | jq
          inputs:
          - name: tfstate
          params:
            AWS_ACCESS_KEY_ID: ((aws_access_key))
            AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
            AWS_DEFAULT_REGION: ((aws_default_region))
      on_failure:
        do:
        - put: cycloid-events
          params:
            severity: crit
            message: Oops
            title: The deployment of ((project)) owl have failed on ((env)) environment
      on_success:
        do:
        - put: cycloid-events
          params:
            message: Congrats !
            title: Successful deployment of ((project)) owl on ((env)) environment
