name: My Demo
canonical: 187-my_demo
author: Pascal Gasp
description: demo
type: stack
image: ""
keywords:
- demo
- provider:aws
technologies:
- technology: stackcraft
  version: "1"
config:
  pipeline:
    pipeline:
      path: pipeline/terraform-pipeline.yaml
    variables:
      path: pipeline/variables.sample.yaml
  terraform:
    187-my_demo:
      destination: ($ project $)/terraform/($ environment $)/187-my_demo.tf
      path: terraform/187-my_demo.tf.sample
