name: My Demo
canonical: 187-my_demo
author: Pascal Gasp
description: demo
type: stack
image: ""
keywords:
- demo
- provider:aws
technologies:
- technology: stackcraft
  version: "1"
config:
  pipeline:
    pipeline:
      path: pipeline/terraform-pipeline.yaml
    variables:
      path: pipeline/variables.sample.yaml
